### ISSUE TITLE
Errors with Lead Creation Example (was: Unable to deploy to SFDC)

### ISSUE THREAD

**Issue by AnilRai** [financialforcedev/alexa-salesforce-flow-skill-examples#1] opened 2016-10-26 20:58 UTC
Hi
when i follow the instructions and click on deploy to sales force, i see an error.
When i login to sfdc, i see the below error reported

Alexa_Slot_Number (Variable) - The scale of "Alexa_Slot_Number" can't be null.

Would you know what is the problem?

**Comment by afawcett** [comment] 2016-10-26 22:23
Apologies, this has now been fixed, please try again.

**Comment by AnilRai** [comment] 2016-10-26 22:53
Thanks you.
Will try in sometime and update.
Thanks for quick response

**Comment by afawcett** [comment] 2016-10-26 23:25
Your welcome, excited to know how you get on! 👍

**Comment by AnilRai** [comment] 2016-10-27 00:40
On the github deploy page, it prints below....But i logged into SFDC and
checked and it has deployed successfully.
Thanks for your help.

Deployment Started
Status: Queued
Error: error
Error: error
Error: error
Error: error

**Comment by AnilRai** [comment] 2016-10-27 00:40
i will do rest of the stuff tomorrow and keep you posted.
Thanks
Anil

**Comment by AnilRai** [comment] 2016-10-27 15:36
Hi Andrew,

While i am testing, I get
      "text": "Error running Flow invalid_grant - authentication failure"

In your blog, in one of the step, you mention
Locate these lines and update with your Salesforce user name, password and
token(combine these).

I did not understand what is the token here?
I have just entered the user name and password respectively like below

var USER_NAME = "sfdcusernamexxx";
var PASSWORD = "sfdcpwdxxx";

**Comment by AnilRai** [comment] 2016-10-27 15:58
Hi Andrew,

I got this working now. The below commands all work.

You: Ask Jarvis, About favourite things
Response: Tell me your favourite color?
You: My favourite color is Red
Response: What is your favourite number?
You: My favourite number is 42
Response: That is amazing my favourite colour and number is also Red and 42

I want to create something in SFDC. I am not able to get that working.

**Comment by AnilRai** [comment] 2016-10-27 16:16
Sorry for lot of emails....Now i could execute
CreateLead Lead name is Kevin Roberts LeadName After that when i execute :
CreateLead Lead company name is FinancialForce CompanyName I see the below
response { "version": "1.0", "response": { "outputSpeech": { "type":
"PlainText", "text": "Error running Flow The flow doesn't have a variable
with the name Alexa_Say, or the variable doesn't allow input access." },
"shouldEndSession": true }, "sessionAttributes": { "Alexa_Slot_LeadName":
"Kevin Roberts LeadName" } }

**Comment by afawcett** [comment] 2016-11-19 18:48
Hi @AnilRai, really sorry for the lack of response, i have been relocating my family from the UK to the US, but things are start to settle down. Looks like you have got the basic samples going, which is great. Can you list explicitly what your saying to Alexa and i'll type and reproduce. I'll look at this for you asap next week!

**Comment by amanda-nCino** [comment] 2017-07-27 17:43
@AnilRai,
I also had this issue, but fixed it altering the variable (Alexa_Say) on the Create Lead flow to input and output. It successfully created the lead. However, my response at the end was invalid. Hope it helps. I have had same types of issues for two demos. Wondering if Amazon API has changed? I was trying: 
CreateLead To Create a Lead
CreateLead Lead name is {Fred Blogs|LeadName}
CreateLead Lead company name is {FinancialForce|CompanyName}

then 
CreateLead To Create a Lead
CreateLead Lead name is Fred
CreateLead Lead company name is AlphaCorps

**Comment by afawcett** [comment] 2017-07-29 20:38
Thanks for sharing @amanda-nCino 👍 

What error are you now getting?

**Comment by amanda-nCino** [comment] 2017-08-02 03:46
The error message returned is:
“The response is invalid”. On hover it is getting an undefined where it expected a string, etc. but doesn’t provide a line number, more info, etc. which makes it difficult to troubleshoot. My lambda seems to be operating correctly, though. Also, It does create the Lead (I am using that example) in the old manual entry of the intentschema.json but still returns the error.

 I think it is related to the deprecation of the LITERAL type, but I am not sure. I do know that with the new ui skill builder beta (I have been spending time trying to convert it since the ui version provides up-to-newest-standard code), I was not allowed to use the LITERAL type and/or it is “QAIntent” anyway instead of CreateLead intent when I use a custom type - Amazon won’t let you enter the file as it is originally through the beta skill builder. Still perusing documentation.

**Comment by afawcett** [comment] 2017-08-06 18:10
@amanda-nCino hmmm yeah thats a good thought. You can view logs in Amazon go to your Lambada function and find the logging function, it should open a new tab and take you to the logs.

**Comment by TwinkleKDixit** [comment] 2017-08-22 09:54
Hi,
Even i was getting the same error "The response is invalid". I could figure out that the Assignment step after creating Lead was assigning to a variable named Alexa_Say. However in the NodeJS scripts the variable expected is Alexa_Tell. So i changed the name to Alexa_Tell in CreateLead flow. Bingo it started to work.

**Comment by afawcett** [comment] 2017-11-26 00:18
Thanks for sharing @TwinkleKDixit, @amanda-nCino maybe this is your issue?

**Comment by niranjankshirsagar** [comment] 2018-01-01 11:17
what change we have to made in visual flow to work this
I am too getting this error in create lead after speaking the lead name as
Error running Flow The flow doesn't have a variable with the name Alexa_Say, or the variable doesn't allow input access.
I have deployed the latest flows

**Comment by afawcett** [comment] 2018-01-01 18:57
Yes there is a bug in that flow, i have fixed it now. But in your case, best to open the flow in your org and just rename the variable Alexa_Say to Alexa_Tell and this should fix it.

**Closed as completed by afawcett** 2018-01-01 18:57 UTC
Labels: bug

**Comment by niranjankshirsagar** [comment] 2018-01-02 07:00
In a flow there are below listed things as
- Decision hasLeadName
- Assignment AskForLeadName
- Decision HasCompanyName
- Assignment AskCompanyName
- Record Created CreateLead
- Assignment SayLeadCreated

let meknow exaclty where to change the Alexa_Say to Alexa_Tell
there is no veriable listed as Alexa_Tell

I have got error when I provide lead name

Me - Alexa ask jordan to create a lead
Alexa - Tell me the first and last name of your Lead?
Me - lead name is John douglas
Alexa - Error running Flow The flow doesn't have a variable with the name Alexa_Say, or the variable doesn't allow input access.

Let meknow what to do to resolve this

**Comment by afawcett** [comment] 2018-01-04 04:34
Open the Flow in your org via the Flow Design, find the variable in the Flow explorer and rename it. It will update all other references to the variable. Then Save the Flow. This is the easiest way to rename it without having to worry about the other references.
